firmware-update: Fix check for exynos9810 models by removing uh.bin.lz4
Run unzip -p SM-N960F-N960FXXU9FVH1.zip BL* | tar xvf - -C out cm.bin.lz4 keystorage.bin.lz4 param.bin.lz4 sboot.bin.lz4 uh.bin.lz4 up_param.bin.lz4
sboot.bin.lz4
param.bin.lz4
up_param.bin.lz4
cm.bin.lz4
keystorage.bin.lz4
tar: uh.bin.lz4: Not found in archive
tar: Exiting with failure status due to previous errors
Error: Process completed with exit code 2.